player_decision_msg: "Choose one ('1' or 'a' or 'aa' syntax): "
player_decision_dest_msg: "\nChoose destination ('1' or 'a' syntax): "
choice_outside_bounds_msg: Choice must be between 1 and {limit}. Try again.
too_many_letters_msg: Too many letters. Try again.
wrong_syntax_msg: Wrong syntax. Try again.
choice_must_be_in_msg: Choice must be in {list}
possible_pours_msg: "Possible pours: "
possible_destinations_msg: "Possible destinations: "