msg:
  player_decision: "Choose one ('1' or 'a' or 'aa' syntax): "
  player_decision_dest: "\nChoose destination ('1' or 'a' syntax): "
  standard_choice: "Choose one ('1' syntax): "
  choice_outside_bounds: Choice must be between 1 and {}. Try again.
  too_many_letters: Too many letters. Try again.
  wrong_syntax: Wrong syntax. Try again.
  choice_must_be_in: Choice must be in {}
  possible_pours: "Possible pours: "
  possible_destinations: "Possible destinations: "
max_level: 4